### ISSUE TITLE
URL Wrong?

### ISSUE THREAD

**Issue by j0nny55555** [open-nsm/meetings#3]
The 505forensics.com goes to Ghandi hosting? Probably a wrong URL?
on:
https://github.com/open-nsm/meetings/blob/master/04-06-2015/notes.yml

Also, do you have a better recording for the
https://vimeo.com/124270105
Because I can barely understand what you are saying and am very interesting in the presentation

**Comment by busterbytes** [comment]
www.505forensics.com will get you to the right page. 

As for the recording, unfortunately we had technical difficulties that day and this is our only recording. 
The sound quality does improve a little way into the video after we made some adjustments and handed it over to the presenters.
